# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Parse'
  pod 'ParseUI'
  pod 'ParseFacebookUtilsV4'
  pod 'ParseTwitterUtils'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

end
